import type { AppConfig } from "../../template/src/config";

// This is a reference example showing how the config is pre-filled from
// Phase 1 extraction. Scenes are NOT in the config — they are custom .tsx
// files generated by the skill. See the bookstreak-annotated.md for the
// creative reasoning behind the BookStreak video.

export const appConfig: AppConfig = {
  app: {
    name: "BookStreak",
    tagline: "Build a reading habit that survives missed days.",
    icon: "app-icon.png",
    platform: "ios",
  },
  brand: {
    primary: "#E67E22",
    primaryLight: "#FDF2E9",
    background: "#FAFAF8",
    surface: "#FFFFFF",
    textPrimary: "#2D2D2D",
    textSecondary: "#6B7280",
    success: "#27AE60",
    danger: "#E74C3C",
    accent: "#B8590E",
  },
  video: {
    fps: 30,
    width: 886,
    height: 1920,
    device: "iphone-15",
    backgroundMusic: "background-music.mp3",
    backgroundMusicVolume: 0.3,
  },
};
